<?php
// ISO-3166-2 von 2025-07-28 updated by chatgpt

$country_data = [
    ['code' => 'AF', 'name' => 'Afghanistan', 'nameeng' => 'Afghanistan', 'latitude' => 33.0, 'longitude' => 65],
    ['code' => 'AX', 'name' => 'Alandinseln', 'nameeng' => 'Aland Islands', 'latitude' => 60.1166, 'longitude' => 19.9],
    ['code' => 'AL', 'name' => 'Albanien', 'nameeng' => 'Albania', 'latitude' => 41.0, 'longitude' => 20],
    ['code' => 'DZ', 'name' => 'Algerien', 'nameeng' => 'Algeria', 'latitude' => 28.0, 'longitude' => 3],
    ['code' => 'AS', 'name' => 'Amerikanisch-Samoa', 'nameeng' => 'American Samoa', 'latitude' => -14.3333, 'longitude' => -170],
    ['code' => 'AD', 'name' => 'Andorra', 'nameeng' => 'Andorra', 'latitude' => 42.5, 'longitude' => 1.5],
    ['code' => 'AO', 'name' => 'Angola', 'nameeng' => 'Angola', 'latitude' => -12.5, 'longitude' => 18.5],
    ['code' => 'AI', 'name' => 'Anguilla', 'nameeng' => 'Anguilla', 'latitude' => 18.25, 'longitude' => -63.1667],
    ['code' => 'AQ', 'name' => 'Antarktis', 'nameeng' => 'Antarctica', 'latitude' => -90.0, 'longitude' => 0],
    ['code' => 'AG', 'name' => 'Antigua und Barbuda', 'nameeng' => 'Antigua and Barbuda', 'latitude' => 17.05, 'longitude' => -61.8],
    ['code' => 'AR', 'name' => 'Argentinien', 'nameeng' => 'Argentina', 'latitude' => -34.0, 'longitude' => -64],
    ['code' => 'AM', 'name' => 'Armenien', 'nameeng' => 'Armenia', 'latitude' => 40.0, 'longitude' => 45],
    ['code' => 'AW', 'name' => 'Aruba', 'nameeng' => 'Aruba', 'latitude' => 12.5, 'longitude' => -69.9667],
    ['code' => 'AU', 'name' => 'Australien', 'nameeng' => 'Australia', 'latitude' => -27.0, 'longitude' => 133],
    ['code' => 'AT', 'name' => 'Österreich', 'nameeng' => 'Austria', 'latitude' => 47.3333, 'longitude' => 13.3333],
    ['code' => 'AZ', 'name' => 'Aserbaidschan', 'nameeng' => 'Azerbaijan', 'latitude' => 40.5, 'longitude' => 47.5],
    ['code' => 'BS', 'name' => 'Bahamas', 'nameeng' => 'Bahamas', 'latitude' => 24.25, 'longitude' => -76],
    ['code' => 'BH', 'name' => 'Bahrain', 'nameeng' => 'Bahrain', 'latitude' => 26.0, 'longitude' => 50.55],
    ['code' => 'BD', 'name' => 'Bangladesch', 'nameeng' => 'Bangladesh', 'latitude' => 24.0, 'longitude' => 90],
    ['code' => 'BB', 'name' => 'Barbados', 'nameeng' => 'Barbados', 'latitude' => 13.1667, 'longitude' => -59.5333],
    ['code' => 'BY', 'name' => 'Belarus', 'nameeng' => 'Belarus', 'latitude' => 53.0, 'longitude' => 28],
    ['code' => 'BE', 'name' => 'Belgien', 'nameeng' => 'Belgium', 'latitude' => 50.8333, 'longitude' => 4],
    ['code' => 'BZ', 'name' => 'Belize', 'nameeng' => 'Belize', 'latitude' => 17.25, 'longitude' => -88.75],
    ['code' => 'BJ', 'name' => 'Benin', 'nameeng' => 'Benin', 'latitude' => 9.5, 'longitude' => 2.25],
    ['code' => 'BM', 'name' => 'Bermuda', 'nameeng' => 'Bermuda', 'latitude' => 32.3333, 'longitude' => -64.75],
    ['code' => 'BT', 'name' => 'Bhutan', 'nameeng' => 'Bhutan', 'latitude' => 27.5, 'longitude' => 90.5],
    ['code' => 'BO', 'name' => 'Bolivien', 'nameeng' => 'Bolivia', 'latitude' => -17.0, 'longitude' => -65],
    ['code' => 'BQ', 'name' => 'Bonaire, Sint Eustatius und Saba', 'nameeng' => 'Bonaire, Sint Eustatius and Saba', 'latitude' => 12.25, 'longitude' => 68.4667],
    ['code' => 'BA', 'name' => 'Bosnien und Herzegowina', 'nameeng' => 'Bosnia and Herzegovina', 'latitude' => 44.0, 'longitude' => 18],
    ['code' => 'BW', 'name' => 'Botswana', 'nameeng' => 'Botswana', 'latitude' => -22.0, 'longitude' => 24],
    ['code' => 'BV', 'name' => 'Bouvetinsel', 'nameeng' => 'Bouvet Island', 'latitude' => -54.4333, 'longitude' => 3.4],
    ['code' => 'BR', 'name' => 'Brasilien', 'nameeng' => 'Brazil', 'latitude' => -10.0, 'longitude' => -55],
    ['code' => 'IO', 'name' => 'Britisches Territorium im Indischen Ozean', 'nameeng' => 'British Indian Ocean Territory', 'latitude' => -6.0, 'longitude' => 71.5],
    ['code' => 'BN', 'name' => 'Brunei', 'nameeng' => 'Brunei Darussalam', 'latitude' => 4.5, 'longitude' => 114.6667],
    ['code' => 'BG', 'name' => 'Bulgarien', 'nameeng' => 'Bulgaria', 'latitude' => 43.0, 'longitude' => 25],
    ['code' => 'BF', 'name' => 'Burkina Faso', 'nameeng' => 'Burkina Faso', 'latitude' => 13.0, 'longitude' => -2],
    ['code' => 'BI', 'name' => 'Burundi', 'nameeng' => 'Burundi', 'latitude' => -3.5, 'longitude' => 30],
    ['code' => 'KH', 'name' => 'Kambodscha', 'nameeng' => 'Cambodia', 'latitude' => 13.0, 'longitude' => 105],
    ['code' => 'CM', 'name' => 'Kamerun', 'nameeng' => 'Cameroon', 'latitude' => 6.0, 'longitude' => 12],
    ['code' => 'CA', 'name' => 'Kanada', 'nameeng' => 'Canada', 'latitude' => 60.0, 'longitude' => -95],
    ['code' => 'CV', 'name' => 'Kap Verde', 'nameeng' => 'Cabo Verde', 'latitude' => 16.0, 'longitude' => -24],
    ['code' => 'KY', 'name' => 'Kaimaninseln', 'nameeng' => 'Cayman Islands', 'latitude' => 19.5, 'longitude' => -80.5],
    ['code' => 'CF', 'name' => 'Zentralafrikanische Republik', 'nameeng' => 'Central African Republic', 'latitude' => 7.0, 'longitude' => 21],
    ['code' => 'TD', 'name' => 'Tschad', 'nameeng' => 'Chad', 'latitude' => 15.0, 'longitude' => 19],
    ['code' => 'CL', 'name' => 'Chile', 'nameeng' => 'Chile', 'latitude' => -30.0, 'longitude' => -71],
    ['code' => 'CN', 'name' => 'China', 'nameeng' => 'China', 'latitude' => 35.0, 'longitude' => 105],
    ['code' => 'CX', 'name' => 'Weihnachtsinsel', 'nameeng' => 'Christmas Island', 'latitude' => -10.5, 'longitude' => 105.6667],
    ['code' => 'CC', 'name' => 'Kokosinseln', 'nameeng' => 'Cocos (Keeling) Islands', 'latitude' => -12.5, 'longitude' => 96.8333],
    ['code' => 'CO', 'name' => 'Kolumbien', 'nameeng' => 'Colombia', 'latitude' => 4.0, 'longitude' => -72],
    ['code' => 'KM', 'name' => 'Komoren', 'nameeng' => 'Comoros', 'latitude' => -12.1667, 'longitude' => 44.25],
    ['code' => 'CD', 'name' => 'Demokratische Republik Kongo', 'nameeng' => 'The Democratic Republic of the Congo', 'latitude' => 0.0, 'longitude' => 25],
    ['code' => 'CG', 'name' => 'Republik Kongo', 'nameeng' => 'Congo', 'latitude' => -1.0, 'longitude' => 15],
    ['code' => 'CK', 'name' => 'Cookinseln', 'nameeng' => 'Cook Islands', 'latitude' => -21.2333, 'longitude' => -159.7667],
    ['code' => 'CR', 'name' => 'Costa Rica', 'nameeng' => 'Costa Rica', 'latitude' => 10.0, 'longitude' => -84],
    ['code' => 'CI', 'name' => 'Cote d’Ivoire', 'nameeng' => 'Cote dIvoire', 'latitude' => 8.0, 'longitude' => -5],
    ['code' => 'HR', 'name' => 'Kroatien', 'nameeng' => 'Croatia', 'latitude' => 45.1667, 'longitude' => 15.5],
    ['code' => 'CU', 'name' => 'Kuba', 'nameeng' => 'Cuba', 'latitude' => 21.5, 'longitude' => -80],
    ['code' => 'CW', 'name' => 'Curacao', 'nameeng' => 'Curacao', 'latitude' => 12.1167, 'longitude' => 68.9333],
    ['code' => 'CY', 'name' => 'Zypern', 'nameeng' => 'Cyprus', 'latitude' => 35.0, 'longitude' => 33],
    ['code' => 'CZ', 'name' => 'Tschechien', 'nameeng' => 'Czechia', 'latitude' => 49.75, 'longitude' => 15.5],
    ['code' => 'DK', 'name' => 'Dänemark', 'nameeng' => 'Denmark', 'latitude' => 56.0, 'longitude' => 10],
    ['code' => 'DJ', 'name' => 'Dschibuti', 'nameeng' => 'Djibouti', 'latitude' => 11.5, 'longitude' => 43],
    ['code' => 'DM', 'name' => 'Dominica', 'nameeng' => 'Dominica', 'latitude' => 15.4167, 'longitude' => -61.3333],
    ['code' => 'DO', 'name' => 'Dominikanische Republik', 'nameeng' => 'Dominican Republic', 'latitude' => 19.0, 'longitude' => -70.6667],
    ['code' => 'EC', 'name' => 'Ecuador', 'nameeng' => 'Ecuador', 'latitude' => -2.0, 'longitude' => -77.5],
    ['code' => 'EG', 'name' => 'Ägypten', 'nameeng' => 'Egypt', 'latitude' => 27.0, 'longitude' => 30],
    ['code' => 'SV', 'name' => 'El Salvador', 'nameeng' => 'El Salvador', 'latitude' => 13.8333, 'longitude' => -88.9167],
    ['code' => 'GQ', 'name' => 'Äquatorial Guinea', 'nameeng' => 'Equatorial Guinea', 'latitude' => 2.0, 'longitude' => 10],
    ['code' => 'ER', 'name' => 'Eritrea', 'nameeng' => 'Eritrea', 'latitude' => 15.0, 'longitude' => 39],
    ['code' => 'EE', 'name' => 'Estland', 'nameeng' => 'Estonia', 'latitude' => 59.0, 'longitude' => 26],
    ['code' => 'ET', 'name' => 'Äthiopien', 'nameeng' => 'Ethiopia', 'latitude' => 8.0, 'longitude' => 38],
    ['code' => 'FK', 'name' => 'Falklandinseln', 'nameeng' => 'Falkland Islands (Malvinas)', 'latitude' => -51.75, 'longitude' => -59],
    ['code' => 'FO', 'name' => 'Färöer', 'nameeng' => 'Faroe Islands', 'latitude' => 62.0, 'longitude' => -7],
    ['code' => 'FJ', 'name' => 'Fidschi', 'nameeng' => 'Fiji', 'latitude' => -18.0, 'longitude' => 175],
    ['code' => 'FI', 'name' => 'Finnland', 'nameeng' => 'Finland', 'latitude' => 64.0, 'longitude' => 26],
    ['code' => 'FR', 'name' => 'Frankreich', 'nameeng' => 'France', 'latitude' => 46.0, 'longitude' => 2],
    ['code' => 'GF', 'name' => 'Französisch-Guayana', 'nameeng' => 'French Guiana', 'latitude' => 4.0, 'longitude' => -53],
    ['code' => 'PF', 'name' => 'Französisch-Polynesien', 'nameeng' => 'French Polynesia', 'latitude' => -15.0, 'longitude' => -140],
    ['code' => 'TF', 'name' => 'Französische Süd- und Antarktisgebiete', 'nameeng' => 'French Southern Territories', 'latitude' => -43.0, 'longitude' => 67],
    ['code' => 'GA', 'name' => 'Gabun', 'nameeng' => 'Gabon', 'latitude' => -1.0, 'longitude' => 11.75],
    ['code' => 'GM', 'name' => 'Gambia', 'nameeng' => 'Gambia', 'latitude' => 13.4667, 'longitude' => -16.5667],
    ['code' => 'GE', 'name' => 'Georgien', 'nameeng' => 'Georgia', 'latitude' => 42.0, 'longitude' => 43.5],
    ['code' => 'DE', 'name' => 'Deutschland', 'nameeng' => 'Germany', 'latitude' => 51.0, 'longitude' => 9],
    ['code' => 'GH', 'name' => 'Ghana', 'nameeng' => 'Ghana', 'latitude' => 8.0, 'longitude' => -2],
    ['code' => 'GI', 'name' => 'Gibraltar', 'nameeng' => 'Gibraltar', 'latitude' => 36.1833, 'longitude' => -5.3667],
    ['code' => 'GR', 'name' => 'Griechenland', 'nameeng' => 'Greece', 'latitude' => 39.0, 'longitude' => 22],
    ['code' => 'GL', 'name' => 'Grönland', 'nameeng' => 'Greenland', 'latitude' => 72.0, 'longitude' => -40],
    ['code' => 'GD', 'name' => 'Grenada', 'nameeng' => 'Grenada', 'latitude' => 12.1167, 'longitude' => -61.6667],
    ['code' => 'GP', 'name' => 'Guadeloupe', 'nameeng' => 'Guadeloupe', 'latitude' => 16.25, 'longitude' => -61.5833],
    ['code' => 'GU', 'name' => 'Guam', 'nameeng' => 'Guam', 'latitude' => 13.4667, 'longitude' => 144.7833],
    ['code' => 'GT', 'name' => 'Guatemala', 'nameeng' => 'Guatemala', 'latitude' => 15.5, 'longitude' => -90.25],
    ['code' => 'GG', 'name' => 'Guernsey', 'nameeng' => 'Guernsey', 'latitude' => 49.45, 'longitude' => -2.5333],
    ['code' => 'GN', 'name' => 'Guinea', 'nameeng' => 'Guinea', 'latitude' => 11.0, 'longitude' => -10],
    ['code' => 'GW', 'name' => 'Guinea-Bissau', 'nameeng' => 'Guinea-Bissau', 'latitude' => 12.0, 'longitude' => -15],
    ['code' => 'GY', 'name' => 'Guyana', 'nameeng' => 'Guyana', 'latitude' => 5.0, 'longitude' => -59],
    ['code' => 'HT', 'name' => 'Haiti', 'nameeng' => 'Haiti', 'latitude' => 19.0, 'longitude' => -72.4167],
    ['code' => 'HM', 'name' => 'Heard und McDonaldinseln', 'nameeng' => 'Heard Island and McDonald Islands', 'latitude' => -53.1, 'longitude' => 72.5167],
    ['code' => 'VA', 'name' => 'Heiliger Stuhl (Vatikanstadt)', 'nameeng' => 'Holy See (Vatican City State)', 'latitude' => 41.9, 'longitude' => 12.45],
    ['code' => 'HN', 'name' => 'Honduras', 'nameeng' => 'Honduras', 'latitude' => 15.0, 'longitude' => -86.5],
    ['code' => 'HK', 'name' => 'Hongkong', 'nameeng' => 'Hong Kong', 'latitude' => 22.25, 'longitude' => 114.1667],
    ['code' => 'HU', 'name' => 'Ungarn', 'nameeng' => 'Hungary', 'latitude' => 47.0, 'longitude' => 20],
    ['code' => 'IS', 'name' => 'Island', 'nameeng' => 'Iceland', 'latitude' => 65.0, 'longitude' => -18],
    ['code' => 'IN', 'name' => 'Indien', 'nameeng' => 'India', 'latitude' => 20.0, 'longitude' => 77],
    ['code' => 'ID', 'name' => 'Indonesien', 'nameeng' => 'Indonesia', 'latitude' => -5.0, 'longitude' => 120],
    ['code' => 'IR', 'name' => 'Iran', 'nameeng' => 'Iran', 'latitude' => 32.0, 'longitude' => 53],
    ['code' => 'IQ', 'name' => 'Irak', 'nameeng' => 'Iraq', 'latitude' => 33.0, 'longitude' => 44],
    ['code' => 'IE', 'name' => 'Irland', 'nameeng' => 'Ireland', 'latitude' => 53.0, 'longitude' => -8],
    ['code' => 'IM', 'name' => 'Isle of Man', 'nameeng' => 'Isle of Man', 'latitude' => 54.15, 'longitude' => -4.4833],
    ['code' => 'IL', 'name' => 'Israel', 'nameeng' => 'Israel', 'latitude' => 31.5, 'longitude' => 34.75],
    ['code' => 'IT', 'name' => 'Italien', 'nameeng' => 'Italy', 'latitude' => 42.8333, 'longitude' => 12.8333],
    ['code' => 'JM', 'name' => 'Jamaika', 'nameeng' => 'Jamaica', 'latitude' => 18.25, 'longitude' => -77.5],
    ['code' => 'JP', 'name' => 'Japan', 'nameeng' => 'Japan', 'latitude' => 36.0, 'longitude' => 138],
    ['code' => 'JE', 'name' => 'Jersey', 'nameeng' => 'Jersey', 'latitude' => 49.19, 'longitude' => -2.11],
    ['code' => 'JO', 'name' => 'Jordanien', 'nameeng' => 'Jordan', 'latitude' => 31.0, 'longitude' => 36],
    ['code' => 'KZ', 'name' => 'Kasachstan', 'nameeng' => 'Kazakhstan', 'latitude' => 48.0, 'longitude' => 68],
    ['code' => 'KE', 'name' => 'Kenia', 'nameeng' => 'Kenya', 'latitude' => 1.0, 'longitude' => 38],
    ['code' => 'KI', 'name' => 'Kiribati', 'nameeng' => 'Kiribati', 'latitude' => 1.4167, 'longitude' => 173],
    ['code' => 'KP', 'name' => 'North Korea', 'nameeng' => 'North Korea', 'latitude' => 40.0, 'longitude' => 127],
    ['code' => 'KR', 'name' => 'South Korea', 'nameeng' => 'South Korea', 'latitude' => 37.0, 'longitude' => 127.5],
    ['code' => 'KW', 'name' => 'Kuwait', 'nameeng' => 'Kuwait', 'latitude' => 29.3375, 'longitude' => 47.6581],
    ['code' => 'KG', 'name' => 'Kirgisistan', 'nameeng' => 'Kyrgyzstan', 'latitude' => 41.0, 'longitude' => 75],
    ['code' => 'LA', 'name' => 'Lao', 'nameeng' => 'Lao', 'latitude' => 18.0, 'longitude' => 105],
    ['code' => 'LV', 'name' => 'Lettland', 'nameeng' => 'Latvia', 'latitude' => 57.0, 'longitude' => 25],
    ['code' => 'LB', 'name' => 'Libanon', 'nameeng' => 'Lebanon', 'latitude' => 33.8333, 'longitude' => 35.8333],
    ['code' => 'LS', 'name' => 'Lesotho', 'nameeng' => 'Lesotho', 'latitude' => -29.5, 'longitude' => 28.5],
    ['code' => 'LR', 'name' => 'Liberia', 'nameeng' => 'Liberia', 'latitude' => 6.5, 'longitude' => -9.5],
    ['code' => 'LY', 'name' => 'Libyen', 'nameeng' => 'Libya', 'latitude' => 25.0, 'longitude' => 17],
    ['code' => 'LI', 'name' => 'Liechtenstein', 'nameeng' => 'Liechtenstein', 'latitude' => 47.1667, 'longitude' => 9.5333],
    ['code' => 'LT', 'name' => 'Litauen', 'nameeng' => 'Lithuania', 'latitude' => 56.0, 'longitude' => 24],
    ['code' => 'LU', 'name' => 'Luxemburg', 'nameeng' => 'Luxembourg', 'latitude' => 49.75, 'longitude' => 6.1667],
    ['code' => 'MO', 'name' => 'Macao', 'nameeng' => 'Macao', 'latitude' => 22.1667, 'longitude' => 113.55],
    ['code' => 'MK', 'name' => 'Nordmazedonien', 'nameeng' => 'North Macedonia', 'latitude' => 41.8333, 'longitude' => 22],
    ['code' => 'MG', 'name' => 'Madagaskar', 'nameeng' => 'Madagascar', 'latitude' => -20.0, 'longitude' => 47],
    ['code' => 'MW', 'name' => 'Malawi', 'nameeng' => 'Malawi', 'latitude' => -13.5, 'longitude' => 34],
    ['code' => 'MY', 'name' => 'Malaysia', 'nameeng' => 'Malaysia', 'latitude' => 2.5, 'longitude' => 112.5],
    ['code' => 'MV', 'name' => 'Malediven', 'nameeng' => 'Maldives', 'latitude' => 3.25, 'longitude' => 73],
    ['code' => 'ML', 'name' => 'Mali', 'nameeng' => 'Mali', 'latitude' => 17.0, 'longitude' => -4],
    ['code' => 'MT', 'name' => 'Malta', 'nameeng' => 'Malta', 'latitude' => 35.8333, 'longitude' => 14.5833],
    ['code' => 'MH', 'name' => 'Marshallinseln', 'nameeng' => 'Marshall Islands', 'latitude' => 9.0, 'longitude' => 168],
    ['code' => 'MQ', 'name' => 'Martinique', 'nameeng' => 'Martinique', 'latitude' => 14.6667, 'longitude' => -61],
    ['code' => 'MR', 'name' => 'Mauretanien', 'nameeng' => 'Mauritania', 'latitude' => 20.0, 'longitude' => -12],
    ['code' => 'MU', 'name' => 'Mauritius', 'nameeng' => 'Mauritius', 'latitude' => -20.2833, 'longitude' => 57.55],
    ['code' => 'YT', 'name' => 'Mayotte', 'nameeng' => 'Mayotte', 'latitude' => -12.8333, 'longitude' => 45.1667],
    ['code' => 'MX', 'name' => 'Mexiko', 'nameeng' => 'Mexico', 'latitude' => 23.0, 'longitude' => -102],
    ['code' => 'FM', 'name' => 'Micronesia', 'nameeng' => 'Micronesia', 'latitude' => 6.9167, 'longitude' => 158.25],
    ['code' => 'MD', 'name' => 'Moldova', 'nameeng' => 'Moldova', 'latitude' => 47.0, 'longitude' => 29],
    ['code' => 'MC', 'name' => 'Monaco', 'nameeng' => 'Monaco', 'latitude' => 43.7333, 'longitude' => 7.4],
    ['code' => 'MN', 'name' => 'Mongolei', 'nameeng' => 'Mongolia', 'latitude' => 46.0, 'longitude' => 105],
    ['code' => 'ME', 'name' => 'Montenegro', 'nameeng' => 'Montenegro', 'latitude' => 42.0, 'longitude' => 19],
    ['code' => 'MS', 'name' => 'Montserrat', 'nameeng' => 'Montserrat', 'latitude' => 16.75, 'longitude' => -62.2],
    ['code' => 'MA', 'name' => 'Marokko', 'nameeng' => 'Morocco', 'latitude' => 32.0, 'longitude' => -5],
    ['code' => 'MZ', 'name' => 'Mosambik', 'nameeng' => 'Mozambique', 'latitude' => -18.25, 'longitude' => 35],
    ['code' => 'MM', 'name' => 'Myanmar', 'nameeng' => 'Myanmar', 'latitude' => 22.0, 'longitude' => 98],
    ['code' => 'NA', 'name' => 'Namibia', 'nameeng' => 'Namibia', 'latitude' => -22.0, 'longitude' => 17],
    ['code' => 'NR', 'name' => 'Nauru', 'nameeng' => 'Nauru', 'latitude' => -0.5333, 'longitude' => 166.9167],
    ['code' => 'NP', 'name' => 'Nepal', 'nameeng' => 'Nepal', 'latitude' => 28.0, 'longitude' => 84],
    ['code' => 'NL', 'name' => 'Niederlande', 'nameeng' => 'Netherlands', 'latitude' => 52.5, 'longitude' => 5.75],
    ['code' => 'NC', 'name' => 'Neukaledonien', 'nameeng' => 'New Caledonia', 'latitude' => -21.5, 'longitude' => 165.5],
    ['code' => 'NZ', 'name' => 'Neuseeland', 'nameeng' => 'New Zealand', 'latitude' => -41.0, 'longitude' => 174],
    ['code' => 'NI', 'name' => 'Nicaragua', 'nameeng' => 'Nicaragua', 'latitude' => 13.0, 'longitude' => -85],
    ['code' => 'NE', 'name' => 'Niger', 'nameeng' => 'Niger', 'latitude' => 16.0, 'longitude' => 8],
    ['code' => 'NG', 'name' => 'Nigeria', 'nameeng' => 'Nigeria', 'latitude' => 10.0, 'longitude' => 8],
    ['code' => 'NU', 'name' => 'Niue', 'nameeng' => 'Niue', 'latitude' => -19.0333, 'longitude' => -169.8667],
    ['code' => 'NF', 'name' => 'Norfolkinsel', 'nameeng' => 'Norfolk Island', 'latitude' => -29.0333, 'longitude' => 167.95],
    ['code' => 'MP', 'name' => 'Nördliche Marianen', 'nameeng' => 'Northern Mariana Islands', 'latitude' => 15.2, 'longitude' => 145.75],
    ['code' => 'NO', 'name' => 'Norwegen', 'nameeng' => 'Norway', 'latitude' => 62.0, 'longitude' => 10],
    ['code' => 'OM', 'name' => 'Oman', 'nameeng' => 'Oman', 'latitude' => 21.0, 'longitude' => 57],
    ['code' => 'PK', 'name' => 'Pakistan', 'nameeng' => 'Pakistan', 'latitude' => 30.0, 'longitude' => 70],
    ['code' => 'PW', 'name' => 'Palau', 'nameeng' => 'Palau', 'latitude' => 7.5, 'longitude' => 134.5],
    ['code' => 'PS', 'name' => 'Palestine', 'nameeng' => 'Palestine', 'latitude' => 32.0, 'longitude' => 35.25],
    ['code' => 'PA', 'name' => 'Panama', 'nameeng' => 'Panama', 'latitude' => 9.0, 'longitude' => -80],
    ['code' => 'PG', 'name' => 'Papua-Neuguinea', 'nameeng' => 'Papua New Guinea', 'latitude' => -6.0, 'longitude' => 147],
    ['code' => 'PY', 'name' => 'Paraguay', 'nameeng' => 'Paraguay', 'latitude' => -23.0, 'longitude' => -58],
    ['code' => 'PE', 'name' => 'Peru', 'nameeng' => 'Peru', 'latitude' => -10.0, 'longitude' => -76],
    ['code' => 'PH', 'name' => 'Philippinen', 'nameeng' => 'Philippines', 'latitude' => 13.0, 'longitude' => 122],
    ['code' => 'PN', 'name' => 'Pitcairninseln', 'nameeng' => 'Pitcairn Islands', 'latitude' => -25.0666, 'longitude' => -130.1],
    ['code' => 'PL', 'name' => 'Polen', 'nameeng' => 'Poland', 'latitude' => 52.0, 'longitude' => 20],
    ['code' => 'PT', 'name' => 'Portugal', 'nameeng' => 'Portugal', 'latitude' => 39.5, 'longitude' => -8],
    ['code' => 'PR', 'name' => 'Puerto Rico', 'nameeng' => 'Puerto Rico', 'latitude' => 18.25, 'longitude' => -66.5],
    ['code' => 'QA', 'name' => 'Katar', 'nameeng' => 'Qatar', 'latitude' => 25.5, 'longitude' => 51.25],
    ['code' => 'RE', 'name' => 'Reunion', 'nameeng' => 'Reunion', 'latitude' => -21.1, 'longitude' => 55.6],
    ['code' => 'RO', 'name' => 'Rumänien', 'nameeng' => 'Romania', 'latitude' => 46.0, 'longitude' => 25],
    ['code' => 'RU', 'name' => 'Russland', 'nameeng' => 'Russian Federation', 'latitude' => 60.0, 'longitude' => 100],
    ['code' => 'RW', 'name' => 'Ruanda', 'nameeng' => 'Rwanda', 'latitude' => -2.0, 'longitude' => 30],
    ['code' => 'BL', 'name' => 'Saint-Barthelemy', 'nameeng' => 'Saint Barthelemy', 'latitude' => 17.8979, 'longitude' => -62.8505],
    ['code' => 'SH', 'name' => 'St. Helena', 'nameeng' => 'Saint Helena', 'latitude' => -15.9333, 'longitude' => -5.7],
    ['code' => 'KN', 'name' => 'St. Kitts und Nevis', 'nameeng' => 'Saint Kitts and Nevis', 'latitude' => 17.3333, 'longitude' => -62.75],
    ['code' => 'LC', 'name' => 'St. Lucia', 'nameeng' => 'Saint Lucia', 'latitude' => 13.8833, 'longitude' => -61.1333],
    ['code' => 'MF', 'name' => 'St. Martin (franz. Teil)', 'nameeng' => 'Saint Martin', 'latitude' => 18.0731, 'longitude' => -63.0822],
    ['code' => 'PM', 'name' => 'St. Pierre und Miquelon', 'nameeng' => 'Saint Pierre and Miquelon', 'latitude' => 46.8333, 'longitude' => -56.3333],
    ['code' => 'VC', 'name' => 'St. Vincent und die Grenadinen', 'nameeng' => 'Saint Vincent and the Grenadines', 'latitude' => 13.25, 'longitude' => -61.2],
    ['code' => 'WS', 'name' => 'Samoa', 'nameeng' => 'Samoa', 'latitude' => -13.5833, 'longitude' => -172.3333],
    ['code' => 'SM', 'name' => 'San Marino', 'nameeng' => 'San Marino', 'latitude' => 43.7667, 'longitude' => 12.4167],
    ['code' => 'ST', 'name' => 'Sao Tome und Principe', 'nameeng' => 'Sao Tome and Principe', 'latitude' => 1.0, 'longitude' => 7],
    ['code' => 'SA', 'name' => 'Saudi-Arabien', 'nameeng' => 'Saudi Arabia', 'latitude' => 25.0, 'longitude' => 45],
    ['code' => 'SN', 'name' => 'Senegal', 'nameeng' => 'Senegal', 'latitude' => 14.0, 'longitude' => -14],
    ['code' => 'RS', 'name' => 'Serbien', 'nameeng' => 'Serbia', 'latitude' => 44.0, 'longitude' => 21],
    ['code' => 'SC', 'name' => 'Seychellen', 'nameeng' => 'Seychelles', 'latitude' => -4.5833, 'longitude' => 55.6667],
    ['code' => 'SL', 'name' => 'Sierra Leone', 'nameeng' => 'Sierra Leone', 'latitude' => 8.5, 'longitude' => -11.5],
    ['code' => 'SG', 'name' => 'Singapur', 'nameeng' => 'Singapore', 'latitude' => 1.3667, 'longitude' => 103.8],
    ['code' => 'SX', 'name' => 'Sint Maarten', 'nameeng' => 'Sint Maarten', 'latitude' => 18.0167, 'longitude' => 63.05],
    ['code' => 'SK', 'name' => 'Slovakia (Slovak Republic)', 'nameeng' => 'Slovakia (Slovak Republic)', 'latitude' => 48.6667, 'longitude' => 19.5],
    ['code' => 'SI', 'name' => 'Slowenien', 'nameeng' => 'Slovenia', 'latitude' => 46.0, 'longitude' => 15],
    ['code' => 'SB', 'name' => 'Salomonen', 'nameeng' => 'Solomon Islands', 'latitude' => -8.0, 'longitude' => 159],
    ['code' => 'SO', 'name' => 'Somalia', 'nameeng' => 'Somalia', 'latitude' => 10.0, 'longitude' => 49],
    ['code' => 'ZA', 'name' => 'Südafrika', 'nameeng' => 'South Africa', 'latitude' => -29.0, 'longitude' => 24],
    ['code' => 'GS', 'name' => 'Südgeorgien und die Südlichen Sandwichinseln', 'nameeng' => 'South Georgia and the South Sandwich Islands', 'latitude' => -54.5, 'longitude' => -37],
    ['code' => 'SS', 'name' => 'Südsudan', 'nameeng' => 'South Sudan', 'latitude' => 4.85, 'longitude' => 31.6],
    ['code' => 'ES', 'name' => 'Spanien', 'nameeng' => 'Spain', 'latitude' => 40.0, 'longitude' => -4],
    ['code' => 'LK', 'name' => 'Sri Lanka', 'nameeng' => 'Sri Lanka', 'latitude' => 7.0, 'longitude' => 81],
    ['code' => 'SD', 'name' => 'Sudan', 'nameeng' => 'Sudan', 'latitude' => 15.0, 'longitude' => 30],
    ['code' => 'SR', 'name' => 'Surinam', 'nameeng' => 'Suriname', 'latitude' => 4.0, 'longitude' => -56],
    ['code' => 'SJ', 'name' => 'Spitzbergen und Jan Mayen', 'nameeng' => 'Svalbard and Jan Mayen', 'latitude' => 78.0, 'longitude' => 20],
    ['code' => 'SZ', 'name' => 'Eswatini', 'nameeng' => 'Eswatini', 'latitude' => -26.5, 'longitude' => 31.5],
    ['code' => 'SE', 'name' => 'Schweden', 'nameeng' => 'Sweden', 'latitude' => 62.0, 'longitude' => 15],
    ['code' => 'CH', 'name' => 'Schweiz', 'nameeng' => 'Switzerland', 'latitude' => 47.0, 'longitude' => 8],
    ['code' => 'SY', 'name' => 'Syrien', 'nameeng' => 'Syria', 'latitude' => 35.0, 'longitude' => 38],
    ['code' => 'TW', 'name' => 'Taiwan', 'nameeng' => 'Taiwan', 'latitude' => 23.5, 'longitude' => 121],
    ['code' => 'TJ', 'name' => 'Tadschikistan', 'nameeng' => 'Tajikistan', 'latitude' => 39.0, 'longitude' => 71],
    ['code' => 'TZ', 'name' => 'Tansania', 'nameeng' => 'Tanzania', 'latitude' => -6.0, 'longitude' => 35],
    ['code' => 'TH', 'name' => 'Thailand', 'nameeng' => 'Thailand', 'latitude' => 15.0, 'longitude' => 100],
    ['code' => 'TL', 'name' => 'Osttimor', 'nameeng' => 'Timor-Leste', 'latitude' => -8.5666, 'longitude' => 125.5666],
    ['code' => 'TG', 'name' => 'Togo', 'nameeng' => 'Togo', 'latitude' => 8.0, 'longitude' => 1.1667],
    ['code' => 'TK', 'name' => 'Tokelau', 'nameeng' => 'Tokelau', 'latitude' => -9.0, 'longitude' => -172],
    ['code' => 'TO', 'name' => 'Tonga', 'nameeng' => 'Tonga', 'latitude' => -20.0, 'longitude' => -175],
    ['code' => 'TT', 'name' => 'Trinidad und Tobago', 'nameeng' => 'Trinidad and Tobago', 'latitude' => 11.0, 'longitude' => -61],
    ['code' => 'TN', 'name' => 'Tunesien', 'nameeng' => 'Tunisia', 'latitude' => 34.0, 'longitude' => 9],
    ['code' => 'TR', 'name' => 'Türkei', 'nameeng' => 'Turkey', 'latitude' => 39.0, 'longitude' => 35],
    ['code' => 'TM', 'name' => 'Turkmenistan', 'nameeng' => 'Turkmenistan', 'latitude' => 40.0, 'longitude' => 60],
    ['code' => 'TC', 'name' => 'Turks and Caicos Islands', 'nameeng' => 'Turks and Caicos Islands', 'latitude' => 21.75, 'longitude' => -71.5833],
    ['code' => 'TV', 'name' => 'Tuvalu', 'nameeng' => 'Tuvalu', 'latitude' => -8.0, 'longitude' => 178],
    ['code' => 'UG', 'name' => 'Uganda', 'nameeng' => 'Uganda', 'latitude' => 1.0, 'longitude' => 32],
    ['code' => 'UA', 'name' => 'Ukraine', 'nameeng' => 'Ukraine', 'latitude' => 49.0, 'longitude' => 32],
    ['code' => 'AE', 'name' => 'Vereinigte Arabische Emirate', 'nameeng' => 'United Arab Emirates', 'latitude' => 24.0, 'longitude' => 54],
    ['code' => 'GB', 'name' => 'United Kingdom', 'nameeng' => 'United Kingdom', 'latitude' => 54.0, 'longitude' => -2],
    ['code' => 'US', 'name' => 'Vereinigte Staaten', 'nameeng' => 'United States of America', 'latitude' => 38.0, 'longitude' => -97],
    ['code' => 'UM', 'name' => 'United States Minor Outlying Islands', 'nameeng' => 'United States Minor Outlying Islands', 'latitude' => 19.2833, 'longitude' => 166.6],
    ['code' => 'UY', 'name' => 'Uruguay', 'nameeng' => 'Uruguay', 'latitude' => -33.0, 'longitude' => -56],
    ['code' => 'UZ', 'name' => 'Usbekistan', 'nameeng' => 'Uzbekistan', 'latitude' => 41.0, 'longitude' => 64],
    ['code' => 'VU', 'name' => 'Vanuatu', 'nameeng' => 'Vanuatu', 'latitude' => -16.0, 'longitude' => 167],
    ['code' => 'VE', 'name' => 'Venezuela', 'nameeng' => 'Venezuela', 'latitude' => 8.0, 'longitude' => -66],
    ['code' => 'VN', 'name' => 'Vietnam', 'nameeng' => 'Vietnam', 'latitude' => 16.0, 'longitude' => 106],
    ['code' => 'VG', 'name' => 'Britische Jungferninseln', 'nameeng' => 'British Virgin Islands', 'latitude' => 18.5, 'longitude' => -64.5],
    ['code' => 'VI', 'name' => 'Vereinigte Staaten Virgin Islands', 'nameeng' => 'United States Virgin Islands', 'latitude' => 18.3333, 'longitude' => -64.8333],
    ['code' => 'WF', 'name' => 'Wallis und Futuna', 'nameeng' => 'Wallis and Futuna', 'latitude' => -13.3, 'longitude' => -176.2],
    ['code' => 'EH', 'name' => 'West Sahara', 'nameeng' => 'Western Sahara', 'latitude' => 24.5, 'longitude' => -13],
    ['code' => 'YE', 'name' => 'Jemen', 'nameeng' => 'Yemen', 'latitude' => 15.0, 'longitude' => 48],
    ['code' => 'ZM', 'name' => 'Sambia', 'nameeng' => 'Zambia', 'latitude' => -15.0, 'longitude' => 30],
    ['code' => 'ZW', 'name' => 'Simbabwe', 'nameeng' => 'Zimbabwe', 'latitude' => -20.0, 'longitude' => 30],
    ['code' => 'XK', 'name' => 'Kosovo', 'nameeng' => 'Kosovo', 'latitude' => 42.52, 'longitude' => 21],
    ['code' => 'ZZ', 'name' => 'International oder privat', 'nameeng' => 'international or private', 'latitude' => 52.0, 'longitude' => 8],
	['code' => 'DD', 'name' => 'Deutsche Demokratische Republik (ehemals)', 'nameeng' => 'German Democratic Republic (former)', 'latitude' => 52.0, 'longitude' => 13.0],
    ['code' => 'SU', 'name' => 'Sowjetunion (ehemals)', 'nameeng' => 'Soviet Union (former)', 'latitude' => 55.0, 'longitude' => 37.0],
    ['code' => 'YU', 'name' => 'Jugoslawien (ehemals)', 'nameeng' => 'Yugoslavia (former)', 'latitude' => 44.0, 'longitude' => 20.0],
    ['code' => 'CS', 'name' => 'Tschechoslowakei (ehemals)', 'nameeng' => 'Czechoslovakia (former)', 'latitude' => 49.75, 'longitude' => 15.5],
    ['code' => 'ZR', 'name' => 'Zaire (ehemals)', 'nameeng' => 'Zaire (former)', 'latitude' => 0.0, 'longitude' => 25.0],
    ['code' => 'NT', 'name' => 'Neutral-Moresnet (historisch)', 'nameeng' => 'Neutral Moresnet (historical)', 'latitude' => 50.7167, 'longitude' => 6.0333],
    ['code' => 'AN', 'name' => 'Niederländische Antillen (ehemals)', 'nameeng' => 'Netherlands Antilles (former)', 'latitude' => 12.05, 'longitude' => -68.9167],
    ['code' => 'BU', 'name' => 'Birma (ehemals)', 'nameeng' => 'Burma (former)', 'latitude' => 21.9162, 'longitude' => 95.956],
    ['code' => 'TP', 'name' => 'Osttimor (ehemals)', 'nameeng' => 'East Timor (former)', 'latitude' => -8.55, 'longitude' => 125.5167],
	['code' => 'MK', 'name' => 'Mazedonien (ehemals)', 'nameeng' => 'Macedonia (former)', 'latitude' => 41.6, 'longitude' => 21.7],
];
